version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: codulgi_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: codulgi_db
      MYSQL_USER: codulgi
      MYSQL_PASSWORD: codul1234
    command:
      - --default-authentication-plugin=mysql_native_password
    ports:
      - "6604:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: