spring:
  datasource :
    url: jdbc:mariadb://localhost:3306/codulgi_db
    username: codulgi
    password: codul1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect